language: c
os:
  - linux
  - osx
  - windows
env:
  - CONFIG=Debug
  - CONFIG=Release
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then sudo apt-get install -y doxygen cmake3 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then brew install doxygen ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]] ; then choco install doxygen.portable ; fi
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=~/.local -DCMAKE_BUILD_TYPE:STRING=$CONFIG ..
  - cmake --build . --config $CONFIG
  - cd test
  - ctest -C Release .
  - cd ..
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]] ; then cpack -G TGZ ; fi